// backend/quotes.js
// 150 citations qualitatives avec auteur pour Memento Mori

export const QUOTES = [
  // --- STOÏCISME & PHILOSOPHIE ---
  "Ce qui trouble les hommes, ce ne sont pas les choses, mais les jugements qu’ils portent sur les choses. – Épictète",
  "Ne gaspille plus de temps à discuter de ce que doit être un homme de bien. Sois-en un. – Marc Aurèle",
  "La vie n’est pas courte, mais nous en perdons beaucoup. – Sénèque",
  "L’obstacle est le chemin. – Marc Aurèle",
  "Tu as pouvoir sur ton esprit, pas sur les événements. – Marc Aurèle",
  "Nous mourons un peu chaque jour. – Sénèque",
  "Celui qui a un pourquoi peut endurer presque n’importe quel comment. – Nietzsche",
  "Ne cherche pas à ce que les événements arrivent comme tu veux, mais veux les événements comme ils arrivent. – Épictète",
  "Le vrai bonheur est de jouir du présent sans dépendre de l’avenir. – Sénèque",
  "La richesse consiste bien plus dans l’usage que dans la possession. – Aristote",
  "La mort sourit à tous, tout ce qu’un homme peut faire est de sourire en retour. – Marc Aurèle",
  "Ce n’est pas parce que les choses sont difficiles que nous n’osons pas, c’est parce que nous n’osons pas qu’elles sont difficiles. – Sénèque",
  "L’homme sage ne se tourmente pas de ce qu’il n’a pas, mais se réjouit de ce qu’il a. – Épictète",
  "Tout ce qui arrive est supportable et vient de la nature. – Marc Aurèle",
  "La colère est une courte folie. – Horace",
  "Connais-toi toi-même. – Socrate",
  "La plus grande victoire, c’est de se vaincre soi-même. – Platon",
  "La liberté est le bien suprême. – Cicéron",
  "Sois le changement que tu veux voir dans le monde. – Gandhi",
  "Un esprit calme apporte la force intérieure. – Bouddha",

  // --- DISCIPLINE & MOTIVATION ---
  "La discipline bat la motivation. – Anonyme",
  "De petits pas chaque jour mènent à de grands résultats. – Anonyme",
  "Ton futur dépend de ce que tu fais aujourd’hui. – Gandhi",
  "Le meilleur moment pour planter un arbre était il y a vingt ans. Le deuxième meilleur est maintenant. – Proverbe chinois",
  "Abandonner est le seul vrai échec. – Anonyme",
  "La douleur de la discipline est plus légère que celle du regret. – Anonyme",
  "Rien ne change si rien ne change. – Anonyme",
  "Tu es plus proche que tu ne le crois. – Anonyme",
  "Commence avant d’être prêt. – Steven Pressfield",
  "Tes habitudes d’aujourd’hui construisent ton destin de demain. – Anonyme",
  "Le succès est la somme de petits efforts répétés jour après jour. – Robert Collier",
  "L’action est la clé fondamentale de tout succès. – Picasso",
  "Les gagnants trouvent des moyens, les perdants trouvent des excuses. – Frank Sinatra",
  "Agis toujours comme s’il était impossible d’échouer. – Winston Churchill",
  "La constance est plus puissante que le talent. – Anonyme",
  "Rien de grand ne s’est accompli sans passion. – Hegel",
  "Fais ce que tu peux, avec ce que tu as, là où tu es. – Theodore Roosevelt",
  "Le progrès se fait hors de la zone de confort. – Anonyme",
  "Celui qui veut réussir trouve un moyen, celui qui ne veut pas trouve une excuse. – Proverbe arabe",
  "Chaque effort compte, même le plus petit. – Anonyme",

  // --- VIE & MORT ---
  "La vie est courte, mais assez longue si tu sais l’utiliser. – Sénèque",
  "Vis comme si tu devais mourir demain. Apprends comme si tu devais vivre toujours. – Gandhi",
  "Le temps est la seule richesse qu’on ne regagne jamais. – Anonyme",
  "La mort n’est rien pour nous. – Épicure",
  "Vivre, c’est choisir. – Sartre",
  "Nous devons tous deux choses : mourir et payer nos impôts. – Benjamin Franklin",
  "À la fin, tu regretteras surtout ce que tu n’as pas fait. – Anonyme",
  "Chaque jour bien vécu rend le lendemain meilleur. – Proverbe indien",
  "La vie se mesure non pas en respirations, mais en moments qui nous coupent le souffle. – Maya Angelou",
  "Ne crains pas la mort, crains de ne jamais vivre. – Marc Aurèle",
  "Nous n’avons pas peu de temps, mais nous en perdons beaucoup. – Sénèque",
  "Chaque souffle est un cadeau. – Anonyme",
  "Vivre, c’est persévérer. – Sénèque",
  "Ton temps est limité, ne le gâche pas en vivant la vie de quelqu’un d’autre. – Steve Jobs",
  "Ce que nous faisons dans la vie résonne dans l’éternité. – Gladiator",
  "La mort est la destination que nous partageons tous. – Steve Jobs",
  "La vie n’a de valeur que par l’usage que nous en faisons. – Montaigne",
  "Un jour tu te réveilleras, et tu n’auras plus le temps de faire ce que tu voulais. – Paulo Coelho",
  "Le moment présent est la seule chose qui nous appartient vraiment. – Bouddha",
  "Chaque matin nous renaissons. Ce que nous faisons aujourd’hui est ce qui compte le plus. – Bouddha",

  // --- PROVERBES & SAGESSSES ---
  "Celui qui déplace une montagne commence toujours par de petites pierres. – Confucius",
  "Tombe sept fois, relève-toi huit. – Proverbe japonais",
  "Un voyage de mille lieues commence toujours par un pas. – Lao Tseu",
  "L’eau perce la pierre, non par force, mais par persistance. – Proverbe chinois",
  "Mieux vaut allumer une bougie que maudire l’obscurité. – Proverbe chinois",
  "La patience est la clé du ciel. – Proverbe turc",
  "L’arbre le plus fort fut autrefois une graine qui a survécu. – Proverbe",
  "Le succès est un escalier, pas une porte. – Dottie Walters",
  "Même l’obscurité la plus profonde ne peut éteindre une étincelle. – Proverbe africain",
  "La pluie tombe goutte à goutte et emplit la jarre. – Proverbe bouddhiste",
  "La fortune sourit aux audacieux. – Virgile",
  "L’habitude est une seconde nature. – Cicéron",
  "Les grandes choses ne sont pas faites par la force, mais par la persévérance. – Samuel Johnson",
  "Ce n’est pas la destination, mais le voyage qui compte. – Proverbe",
  "Le courage n’est pas l’absence de peur, mais la capacité de la vaincre. – Mandela",
  "Il n’est point de bonheur sans courage, ni de vertu sans combat. – Rousseau",
  "Un esprit sain dans un corps sain. – Juvénal",
  "Le savoir n’a de valeur que s’il est partagé. – Proverbe africain",
  "L’expérience est une lanterne attachée dans notre dos, qui n’éclaire que le chemin parcouru. – Confucius",
  "Une mauvaise habitude est d’abord une toile d’araignée, puis un câble d’acier. – Proverbe espagnol",

  // --- INSPIRATION & HUMILITÉ ---
  "Le succès est d’aller d’échec en échec sans perdre son enthousiasme. – Churchill",
  "Le génie est 1% d’inspiration et 99% de transpiration. – Edison",
  "Le bonheur n’est pas d’avoir tout ce que l’on désire, mais d’apprécier ce que l’on a. – Bouddha",
  "La simplicité est la sophistication suprême. – Léonard de Vinci",
  "Les grandes âmes ont de la volonté, les faibles n’ont que des souhaits. – Proverbe chinois",
  "Apprends à obéir avant de commander. – Solon",
  "Le savoir, c’est le pouvoir. – Francis Bacon",
  "La vraie richesse est celle de l’âme. – Sénèque",
  "Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. – Albert Schweitzer",
  "Un esprit qui s’élargit ne revient jamais à sa taille initiale. – Einstein",
  "L’imagination est plus importante que le savoir. – Einstein",
  "Fais de ta vie un rêve, et d’un rêve une réalité. – Saint-Exupéry",
  "L’homme qui déplace des montagnes commence par déplacer de petites pierres. – Confucius",
  "Le plus grand risque est de ne prendre aucun risque. – Mark Zuckerberg",
  "Reste affamé, reste fou. – Steve Jobs",
  "On ne change jamais les choses en combattant la réalité existante. – Buckminster Fuller",
  "Le succès n’est pas final, l’échec n’est pas fatal : c’est le courage de continuer qui compte. – Churchill",
  "Une vie passée à commettre des erreurs est non seulement plus honorable, mais plus utile qu’une vie passée à ne rien faire. – George Bernard Shaw",
  "Tout ce que tu peux imaginer est réel. – Picasso",
  "Les rêves ne fonctionnent que si tu travailles dur. – Anonyme",
];
