name: Deploy memento-mori to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy Docker Image memento-mori
    runs-on: memento-mori # ton runner self-hosted sur le serveur Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t memento-mori .

      - name: Stop existing container
        run: docker stop memento-mori || true

      - name: Remove existing container
        run: docker rm memento-mori || true

      - name: Create .env file from GitHub secrets
        run: |
          echo "VAPID_SUBJECT=${{ secrets.VAPID_SUBJECT }}" >> .env
          echo "VAPID_PUBLIC_KEY=${{ secrets.VAPID_PUBLIC_KEY }}" >> .env
          echo "VAPID_PRIVATE_KEY=${{ secrets.VAPID_PRIVATE_KEY }}" >> .env
          echo "PORT=3001" >> .env
          echo "HOST=0.0.0.0" >> .env

      - name: Start new container
        run: |
          docker run -d \
            --name memento-mori \
            --env-file .env \
            -p 5173:3001 \
            -e DATA_DIR=/data \
            -v /home/ubuntu/memento/data:/data \
            --label com.centurylinklabs.watchtower.enable=false \
            --restart unless-stopped \
            --user 1001:1001 \
            memento-mori

      - name: Wait for container startup
        run: sleep 5
        shell: bash

      - name: Check if docker run
        run: docker ps --filter name=memento-mori --filter status=running --quiet | grep . || exit 1
        shell: bash

      - name: Cleanup old images
        if: always()
        run: docker image prune -f
